### ISSUE TITLE
Use different rendering options for code and results

### ISSUE THREAD

**Issue by holgerbrandl** [imvladikon/jupyter-notebook-viewer#2]
Currently code and results look exactly the same, which makes it harder to read the preview.

Example:
![image](https://user-images.githubusercontent.com/200952/88109571-0b70a800-cbab-11ea-9a87-088355b97313.png)

Maybe the background color could be different?

**Comment by imvladikon** [comment]
Sorry for the late response, I'll check it, but one of the options is using another style
<img width="784" alt="U2ntitled" src="https://user-images.githubusercontent.com/10088963/91898990-328bc080-eca5-11ea-9939-d389373f2837.png">

**Comment by rayanelhelou** [comment]
Thanks for the suggestion. Is there an update on this?

FYI for those who want to choose from existing styles to solve this problem, try these: "markdown", "torpedo" or "foghorn".

**Comment by imvladikon** [comment]
The idea of the themes is precisely about choosing a convenient style. A github-like style is a default theme. Anyway, I've changed this theme, added borders, changed font and font size, etc., in the new version.
![image](https://user-images.githubusercontent.com/10088963/166095990-67fbcf22-7cfe-4f61-83e7-795bddde9b8f.png)
