### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by rayanelhelou** [imvladikon/jupyter-notebook-viewer#5]
Thanks for this great extension! For some reason, it's not working anymore as of the last week or two.
I have to reinstall it every time for it to work again, then a day later it doesn't work again.
Are you facing similar issues?

**Comment by imvladikon** [comment]
I updated the extension, upgraded versions of the dependencies, optimized some parts, and changed the default theme, where I added borders, modified font, font size, etc., in the new version.
